### PR TITLE
migrate to github actions

### PR DESCRIPTION
**Pull request by WebFreak001**
(automatically opened on all repos, please review)

### CODE REVIEW

**Comment by icy** [comment]
@WebFreak001 My apologies, I haven't noticed of your PR. Let's give it a try now.

**Comment by WebFreak001** [comment]
thanks! btw you at dconf?

**Comment by icy** [comment]
> thanks! btw you at dconf?

Not this time unfortunately. Hopefully I can get some proper support next time.

**Comment by icy** [comment]
> thanks! btw you at dconf?

The github-action migration is going well . Thank you a lot for your contribution.

**Pull request merged**
